# Generated by Django 4.2.7 on 2023-11-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_item_item_image_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('PR', 'primary'), ('SE', 'secondary'), ('DA', 'danger')], max_length=2, null=True),
        ),
    ]
