# Generated by Django 4.2.7 on 2023-11-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_item_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('PR', 'primary'), ('SE', 'secondary'), ('DA', 'danger'), ('DK', 'dark')], max_length=2, null=True),
        ),
    ]
