# Generated by Django 4.2.7 on 2023-11-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
