# Generated by Django 4.2.7 on 2023-11-09 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0010_orderitems_ordered_orderitems_user_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
