# Generated by Django 4.2.7 on 2023-11-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_coupon_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='amount',
            field=models.FloatField(default=20),
        ),
    ]
